# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import login_service_cs_pb2 as protos_dot_login__service__cs__pb2


class LoginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RpcLogin = channel.unary_unary(
                '/Login/RpcLogin',
                request_serializer=protos_dot_login__service__cs__pb2.LoginCredentials.SerializeToString,
                response_deserializer=protos_dot_login__service__cs__pb2.LoginResponse.FromString,
                )


class LoginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RpcLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RpcLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.RpcLogin,
                    request_deserializer=protos_dot_login__service__cs__pb2.LoginCredentials.FromString,
                    response_serializer=protos_dot_login__service__cs__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Login', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Login(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RpcLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Login/RpcLogin',
            protos_dot_login__service__cs__pb2.LoginCredentials.SerializeToString,
            protos_dot_login__service__cs__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
