version: "3.9"
services:
  gateway-api:
    build: ./gateway-api
    container_name: gateway-api
    ports:
      - "50052:50052"
    volumes:
      - ./gateway-api:/app
  login-service:
    build: ./login-service
    container_name: login-service
  make-root-service:
    build: ./make-root-service
    container_name: make-root-service
