version: "3.9"
services:

  mysqlDb:
    image: mysql:latest
    container_name: mysqlDb
    restart: always
    volumes:
      - ./mysql/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'b4y_userDb'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  neo4jDb:
    # Docker image to be used
    image: neo4j:latest

    # Hostname
    hostname: neo4jDb

    container_name: neo4jDb

    # The ports that will be accessible from outside the container - HTTP (7474) and Bolt (7687).
    ports:
      - "7474:7474"
      - "7687:7687"
    
    volumes:
      - ./neo4j/data:/data
      - ./plugins:/plugins
    

      # Passes the following environment variables to the container
    environment:
      NEO4J_AUTH : "neo4j/123456789"

    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  db-service:
    build: ./db-service
    container_name: db-service
    volumes:
      - ./db-service:/app
    depends_on:
      mysqlDb:
        condition: service_healthy

  booking_service:
    build: ./booking-service
    container_name: booking_service
    volumes:
      - ./booking-service:/app
    depends_on:
      neo4jDb:
        condition: service_healthy

  gateway-api:
    build: ./gateway-api
    container_name: gateway-api
    ports:
      - "50052:50052"
    volumes:
      - ./gateway-api:/app

  login-service:
    build: ./login-service
    container_name: login-service
    depends_on:
      mysqlDb:
        condition: service_healthy

  make-root-service:
    build: ./make-root-service
    container_name: make-root-service
    volumes:
      - ./make-root-service:/app


#networks:
  #backend-net:
    #name: backend-net
    #external: true

