version: "3.9"
services:
  gateway-api:
    build: ./gatewayApiPack
    container_name: gateway-api
    ports:
      - "50052:50052"
    networks:
      - backend-net
  login-service:
    build: ./loginServicePack
    container_name: login-service
    networks:
      - backend-net

networks:
  backend-net:
    name: backend-net
    external: true