version: "3.9"
services:
  neo4j:
    # Docker image to be used
    image: neo4j:latest

    # Hostname
    hostname: neo4j

    # The ports that will be accessible from outside the container - HTTP (7474) and Bolt (7687).
    ports:
      - "7474:7474"
      - "7687:7687"
    
    volumes:
      - ./neo4j/data:/data

     # Passes the following environment variables to the container
    environment:
      - NEO4J_AUTH=none

  gateway-api:
    build: ./gatewayApiPack
    container_name: gateway-api
    ports:
      - "50052:50052"
    #networks:
      #- backend-net

  login-service:
    build: ./loginServicePack
    container_name: login-service
    #networks:
      #- backend-net

  booking_service:
    build: ./booking-service
    container_name: booking_service
    volumes:
      - ./booking-service:/app

  server:
    build: ./2-OPT
    container_name: server

  client:
    build: ./GatewayAPI
    container_name: client
    ports:
      - "7000:5000"
    volumes:
      - ./GatewayAPI:/app
    environment:
      FLASK_DEBUG: "true"

  #networks:
  #backend-net:
    #name: backend-net
    #external: true